name: Build and Deploy TinaCMS Site

on:
  push:
    branches:
      - main # Change this to your default branch name
env:
  TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
  TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
  TEST: sometext

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm' # Change to 'yarn' or 'pnpm' if applicable

      - name: Install Dependencies
        run: npm ci # Use `yarn install` or `pnpm install` if preferred

      # - name: Build TinaCMS Admin Client
      #   run: npx tinacms build
      #   env:
      #     TINA_PUBLIC_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }}
      #     TINA_TOKEN: ${{ secrets.TINA_TOKEN }}
      #     NEXT_PUBLIC_TINA_CLIENT_ID: ${{ secrets.TINA_PUBLIC_CLIENT_ID }} # Required if using Next.js

      - name: Test output
        run: echo "Test = $TEST; token = $TINA_TOKEN"

      - name: Build Production Website
        run: TINA_PUBLIC_CLIENT_ID=$TINA_PUBLIC_CLIENT_ID TINA_TOKEN=$TINA_TOKEN npm run build
